<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>depchain</groupId>
        <artifactId>DepChain</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>contract</artifactId>
    <name>contract</name>
    <packaging>jar</packaging>

    <dependencies>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.tmio/tuweni-bytes -->
        <dependency>
            <groupId>io.tmio</groupId>
            <artifactId>tuweni-bytes</artifactId>
            <version>2.4.2</version>
            <type>pom</type>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.tmio/tuweni-units -->
        <dependency>
            <groupId>io.tmio</groupId>
            <artifactId>tuweni-units</artifactId>
            <version>2.4.2</version>
            <type>pom</type>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.hyperledger.besu/besu-datatypes -->
        <dependency>
            <groupId>org.hyperledger.besu</groupId>
            <artifactId>besu-datatypes</artifactId>
            <version>25.2.1</version>
            <scope>runtime</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.hyperledger.besu/evm -->
        <dependency>
            <groupId>org.hyperledger.besu</groupId>
            <artifactId>evm</artifactId>
            <version>25.2.1</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>hyperledger-besu</id>
            <url>https://hyperledger.jfrog.io/artifactory/besu-maven</url>
        </repository>
    </repositories>

    <!--build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>depchain.contract.ISTCoinMain</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build-->

</project>
